// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxNILXZnFj4Ghvh2IRo2mlUl_ioF-csXA',
    appId: '1:1035041308923:web:ca6fa627b58f0134c2305e',
    messagingSenderId: '1035041308923',
    projectId: 'wafy-sports',
    authDomain: 'wafy-sports.firebaseapp.com',
    storageBucket: 'wafy-sports.firebasestorage.app',
    measurementId: 'G-V88VV2JCFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKi5DQP0xjFWdtjQXUWjj_PVumSM3Yj5Q',
    appId: '1:1035041308923:android:128ed5d6d169ff6fc2305e',
    messagingSenderId: '1035041308923',
    projectId: 'wafy-sports',
    storageBucket: 'wafy-sports.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPklbqqyEw9Vg-8yPOwFh3jvTCzO9F3LU',
    appId: '1:1035041308923:ios:74d6cb0143b9667bc2305e',
    messagingSenderId: '1035041308923',
    projectId: 'wafy-sports',
    storageBucket: 'wafy-sports.firebasestorage.app',
    iosBundleId: 'com.example.sportsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPklbqqyEw9Vg-8yPOwFh3jvTCzO9F3LU',
    appId: '1:1035041308923:ios:74d6cb0143b9667bc2305e',
    messagingSenderId: '1035041308923',
    projectId: 'wafy-sports',
    storageBucket: 'wafy-sports.firebasestorage.app',
    iosBundleId: 'com.example.sportsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxNILXZnFj4Ghvh2IRo2mlUl_ioF-csXA',
    appId: '1:1035041308923:web:6c2dcae77e136b9ac2305e',
    messagingSenderId: '1035041308923',
    projectId: 'wafy-sports',
    authDomain: 'wafy-sports.firebaseapp.com',
    storageBucket: 'wafy-sports.firebasestorage.app',
    measurementId: 'G-L206B5QHST',
  );

}