// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd_BzlzcQWzsrxDi0dDz5MQWPGsx00iSM',
    appId: '1:791706601942:web:eefdb821a38edaf082fc77',
    messagingSenderId: '791706601942',
    projectId: 'flutterapplication2-4642c',
    authDomain: 'flutterapplication2-4642c.firebaseapp.com',
    storageBucket: 'flutterapplication2-4642c.firebasestorage.app',
    measurementId: 'G-TNQD3SW570',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGNmzJVekyx_SBdndSYZZOKzEEAfx31TI',
    appId: '1:791706601942:android:6c056da99ce0e19c82fc77',
    messagingSenderId: '791706601942',
    projectId: 'flutterapplication2-4642c',
    storageBucket: 'flutterapplication2-4642c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4C3UVnL8aZXu9M3lVy6CLMuS6m7a4MiY',
    appId: '1:791706601942:ios:0ad59006899458d382fc77',
    messagingSenderId: '791706601942',
    projectId: 'flutterapplication2-4642c',
    storageBucket: 'flutterapplication2-4642c.firebasestorage.app',
    iosBundleId: 'com.example.sportsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4C3UVnL8aZXu9M3lVy6CLMuS6m7a4MiY',
    appId: '1:791706601942:ios:0ad59006899458d382fc77',
    messagingSenderId: '791706601942',
    projectId: 'flutterapplication2-4642c',
    storageBucket: 'flutterapplication2-4642c.firebasestorage.app',
    iosBundleId: 'com.example.sportsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAd_BzlzcQWzsrxDi0dDz5MQWPGsx00iSM',
    appId: '1:791706601942:web:87aa6427c6fc0baa82fc77',
    messagingSenderId: '791706601942',
    projectId: 'flutterapplication2-4642c',
    authDomain: 'flutterapplication2-4642c.firebaseapp.com',
    storageBucket: 'flutterapplication2-4642c.firebasestorage.app',
    measurementId: 'G-XLST2PYGF4',
  );

}